DELETE FROM DYNAMIC_PARAMETER WHERE PARAMETER_KEY = 'minInterestRate';
INSERT INTO DYNAMIC_PARAMETER (PARAMETER_KEY, PARAMETER_VALUE) VALUES ('minInterestRate', '0.1');

DELETE FROM DYNAMIC_PARAMETER WHERE PARAMETER_KEY = 'maxInterestRate';
INSERT INTO DYNAMIC_PARAMETER (PARAMETER_KEY, PARAMETER_VALUE) VALUES ('maxInterestRate', '0.5');

DELETE FROM DYNAMIC_PARAMETER WHERE PARAMETER_KEY = 'availableInstallments';
INSERT INTO DYNAMIC_PARAMETER (PARAMETER_KEY, PARAMETER_VALUE) VALUES ('availableInstallments', '6,9,12,24');